### ISSUE TITLE
怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复

### ISSUE THREAD

**Issue by kzq5** [tigerAndBull/LoadAnimatedDemo-ios#15]

**Comment by tigerAndBull** [comment]
如果你使用了`- (void)initWithShimmerAnimated`或者`- (void)initWithOnlySkeleton` 
当前版本会默认选中所有view。 

目前的解决方案： 
在appDelegate初始化的时候选择 
`- (void)initWithDefaultAnimated`或者 `- (void)initWithCustomAnimation`方法，
 然后 再订制你需要的动画，只有注册的组件才会加入。 
如果设置取消选中很有必要，你再联系我，会尽早进行优化。

**Comment by kzq5** [comment]
多谢回复，如果用`initWithDefaultAnimated`或`initWithCustomAnimation`还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒）
<img width="617" alt="default" src="https://user-images.githubusercontent.com/11565042/53147728-6895b200-35e3-11e9-9292-3c4f9e0ad817.png">
还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？

**Comment by kzq5** [comment]
@tigerAndBull

**Comment by tigerAndBull** [comment]
您好，您的做法是一种解决方案，大致思路也不会本质区别。
另外，您说的多样式cell是指？




------------------ 原始邮件 ------------------
发件人: "kzq5"<notifications@github.com>;
发送时间: 2019年2月21日(星期四) 下午2:18
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15)




多谢回复，如果用initWithDefaultAnimated或initWithCustomAnimation还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒）
 
 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？

**Comment by tigerAndBull** [comment]
> 多谢回复，如果用`initWithDefaultAnimated`或`initWithCustomAnimation`还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒）
> <img alt="default" width="617" src="https://user-images.githubusercontent.com/11565042/53147728-6895b200-35e3-11e9-9292-3c4f9e0ad817.png">
> 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？

还有，如果有其他个性化建议，也希望提出。

**Comment by kzq5** [comment]
> 您好，您的做法是一种解决方案，大致思路也不会本质区别。 另外，您说的多样式cell是指？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kzq5"<notifications@github.com>; 发送时间: 2019年2月21日(星期四) 下午2:18 收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>; 抄送: "安文虎"<1429299849@qq.com>; "Comment"<comment@noreply.github.com>; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 多谢回复，如果用initWithDefaultAnimated或initWithCustomAnimation还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒） 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

就是多个分区，多个样式的cell这种，每个cell高度不同，cell的具体显示样式也不同

**Comment by tigerAndBull** [comment]
目前是支持的，如果有什么疑问可以继续联系我，
如果使用masonry布局，只要控制好宽高即可。


------------------ 原始邮件 ------------------
发件人: "kzq5"<notifications@github.com>;
发送时间: 2019年2月21日(星期四) 下午2:26
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15)



 
您好，您的做法是一种解决方案，大致思路也不会本质区别。 另外，您说的多样式cell是指？
 …
 ------------------ 原始邮件 ------------------ 发件人: "kzq5"notifications@github.com; 发送时间: 2019年2月21日(星期四) 下午2:18 收件人: "tigerAndBull/LoadAnimatedDemo-ios"LoadAnimatedDemo-ios@noreply.github.com; 抄送: "安文虎"1429299849@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 多谢回复，如果用initWithDefaultAnimated或initWithCustomAnimation还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒） 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
就是多个分区，多个样式的cell这种，每个cell高度不同，cell的具体显示样式也不同

**Comment by kzq5** [comment]
> 目前是支持的，如果有什么疑问可以继续联系我， 如果使用masonry布局，只要控制好宽高即可。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kzq5"<notifications@github.com>; 发送时间: 2019年2月21日(星期四) 下午2:26 收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>; 抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 您好，您的做法是一种解决方案，大致思路也不会本质区别。 另外，您说的多样式cell是指？ … ------------------ 原始邮件 ------------------ 发件人: "kzq5"notifications@github.com; 发送时间: 2019年2月21日(星期四) 下午2:18 收件人: "tigerAndBull/LoadAnimatedDemo-ios"LoadAnimatedDemo-ios@noreply.github.com; 抄送: "安文虎"1429299849@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 多谢回复，如果用initWithDefaultAnimated或initWithCustomAnimation还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒） 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 就是多个分区，多个样式的cell这种，每个cell高度不同，cell的具体显示样式也不同 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

好的，我昨天用的时候好像不支持，显示的是同一种cell样式，我再试试，多谢

**Comment by tigerAndBull** [comment]
如果section数量也是获取，变化的，最新版本去掉了这个。




------------------ 原始邮件 ------------------
发件人: "kzq5"<notifications@github.com>;
发送时间: 2019年2月21日(星期四) 下午2:31
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15)



 
目前是支持的，如果有什么疑问可以继续联系我， 如果使用masonry布局，只要控制好宽高即可。
 …
 ------------------ 原始邮件 ------------------ 发件人: "kzq5"notifications@github.com; 发送时间: 2019年2月21日(星期四) 下午2:26 收件人: "tigerAndBull/LoadAnimatedDemo-ios"LoadAnimatedDemo-ios@noreply.github.com; 抄送: "安文虎"1429299849@qq.com; "Mention"mention@noreply.github.com; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 您好，您的做法是一种解决方案，大致思路也不会本质区别。 另外，您说的多样式cell是指？ … ------------------ 原始邮件 ------------------ 发件人: "kzq5"notifications@github.com; 发送时间: 2019年2月21日(星期四) 下午2:18 收件人: "tigerAndBull/LoadAnimatedDemo-ios"LoadAnimatedDemo-ios@noreply.github.com; 抄送: "安文虎"1429299849@qq.com; "Comment"comment@noreply.github.com; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) 多谢回复，如果用initWithDefaultAnimated或initWithCustomAnimation还是挺麻烦的，毕竟一个cell中可能就一两个不需要，所以我偷个懒，在这里加个tag的筛选，暂时解决了，后续希望作者可以加上这个功能（我这个垃圾做法就别了，想必作者会有更好的方法，毕竟我只是为了偷懒） 还有现在只支持单一cell样式的骨架，什么时候加上多样式cell呢？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. 就是多个分区，多个样式的cell这种，每个cell高度不同，cell的具体显示样式也不同 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
  
好的，我昨天用的时候好像不支持，显示的是同一种cell样式，我再试试，多谢

**Comment by kzq5** [comment]
@tigerAndBull  好的

**Comment by kzq5** [comment]
@tigerAndBull  多cell可以的，由于我每个section只有一个cell，需要设置一下animatedCount=1.但是section的header没效果，是需要额外设置什么吗

**Comment by tigerAndBull** [comment]
header确实没有支持，
可以添加这个需求，
近期有考虑重构这个框架。




------------------ 原始邮件 ------------------
发件人: "kzq5"<notifications@github.com>;
发送时间: 2019年2月21日(星期四) 下午2:52
收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>;
抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15)




@tigerAndBull  多cell可以的，由于我每个section只有一个cell，需要设置一下animatedCount=1.但是section的header没效果，是需要额外设置什么吗

**Comment by kzq5** [comment]
> 近期有考虑重构这个框架。

嗯，

> header确实没有支持， 可以添加这个需求， 近期有考虑重构这个框架。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "kzq5"<notifications@github.com>; 发送时间: 2019年2月21日(星期四) 下午2:52 收件人: "tigerAndBull/LoadAnimatedDemo-ios"<LoadAnimatedDemo-ios@noreply.github.com>; 抄送: "安文虎"<1429299849@qq.com>; "Mention"<mention@noreply.github.com>; 主题: Re: [tigerAndBull/LoadAnimatedDemo-ios] 怎么设置tableviewcell中部分控件不显示骨架，以及多种样式cell显示骨架，望作者回复 (#15) @tigerAndBull 多cell可以的，由于我每个section只有一个cell，需要设置一下animatedCount=1.但是section的header没效果，是需要额外设置什么吗 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

好的，支持作者

**Comment by tigerAndBull** [comment]
> @tigerAndBull

v1.9.0已发布解决
